###
# This is the place to override the mod_php5_apache2 cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "mod_php5_apache2/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

normal[:mod_php5_apache2][:packages] = [ 'php5-xml',
                                         'php5-common',
                                         'php5-xmlrpc',
                                         'php5-devel',
                                         'php5-gd',
                                         'php5-cli',
                                         'php5-pear-Auth-SASL',
                                         'php5-mysql',
                                         'php5-mcrypt' ]
