###
# This is the place to override the mod_php5_apache2 cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "mod_php5_apache2/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

normal[:mod_php5_apache2][:packages] = [ 'php54-xml',
                                         'php54-common',
                                         'php54-xmlrpc',
                                         # 'php54-devel',
                                         'php54-gd',
                                         'php54-cli',
                                         'php54-pear-Auth-SASL',
                                         'php54-mysql',
                                         'php54-mcrypt' ]
